"""
Accounting Statistics Router - MODULE 5
Advanced Accounting Statistics & Visual Reports
"""
from fastapi import APIRouter, Depends, HTTPException, Query, status
from typing import Optional, List
import logging

from app.dependencies.auth import get_current_user, require_role
from app.services.accounting_stats_service import (
    get_accountant_personal_stats,
    get_admin_global_stats,
    get_accountant_performance,
    get_payment_method_stats,
    get_class_revenue_stats,
    get_activity_timeline
)
from app.models.accounting_stats import (
    AccountantPersonalStatsResponse,
    AdminGlobalStatsResponse,
    AccountantPerformanceResponse,
    PaymentMethodAnalyticsResponse,
    ClassRevenueStatsResponse,
    ActivityTimelineResponse,
    ActivityType
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/accounting", tags=["Accounting Statistics"])


# ==================== ACCOUNTANT PERSONAL STATS (TASK 1) ====================

@router.get("/my-stats")
async def get_my_statistics(
    days_trend: int = Query(default=30, ge=7, le=90, description="Days for trend data"),
    current_user: dict = Depends(get_current_user)
):
    """
    Get personal statistics for the logged-in accountant.
    TASK 1: Accountant Personal Statistics Dashboard
    
    Only accountants can access their own statistics.
    """
    role = current_user.get("role", "").lower()
    
    # Security check - only accountants, admin, root can access
    if role not in ["accountant", "admin", "root"]:
        logger.warning(f"⚠️ Unauthorized statistics access attempt by {current_user.get('email')}")
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied. Accountant role required."
        )
    
    logger.info(f"📊 Loading accountant statistics dashboard for {current_user.get('email')}")
    
    try:
        user_id = current_user.get("id") or current_user.get("user_id")
        school_id = current_user.get("school_id")
        
        if not school_id:
            raise HTTPException(status_code=400, detail="School context required")
        
        stats = get_accountant_personal_stats(
            user_id=user_id,
            user_name=current_user.get("name", "Unknown"),
            user_email=current_user.get("email", "unknown"),
            school_id=school_id,
            days_trend=days_trend
        )
        
        return {"success": True, "data": stats}
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Error getting personal stats: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ==================== ADMIN GLOBAL STATS (TASK 2) ====================

@router.get("/admin/global-stats")
async def get_global_statistics(
    date_from: Optional[str] = Query(None, description="Start date YYYY-MM-DD"),
    date_to: Optional[str] = Query(None, description="End date YYYY-MM-DD"),
    months_trend: int = Query(default=12, ge=3, le=24, description="Months for trend data"),
    current_user: dict = Depends(get_current_user)
):
    """
    Get global statistics for admin dashboard.
    TASK 2: Admin Global Statistics Dashboard
    
    Only admin/root can access global statistics.
    """
    role = current_user.get("role", "")
    if role:
        role = role.lower()
    
    logger.info(f"📊 Admin stats request from {current_user.get('email')} with role: {role}")
    
    # Security check - admin/root only
    if role not in ["admin", "root"]:
        logger.warning(f"⚠️ Unauthorized statistics access attempt by {current_user.get('email')} (role: {role})")
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"Access denied. Admin role required. Current role: {role}"
        )
    
    logger.info(f"📊 Admin accounting statistics generated by {current_user.get('email')}")
    
    try:
        school_id = current_user.get("school_id")
        school_name = current_user.get("school_name", "Unknown School")
        
        if not school_id:
            raise HTTPException(status_code=400, detail="School context required")
        
        stats = get_admin_global_stats(
            school_id=school_id,
            school_name=school_name,
            date_from=date_from,
            date_to=date_to,
            months_trend=months_trend
        )
        
        return {"success": True, "data": stats}
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Error getting global stats: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ==================== ACCOUNTANT PERFORMANCE TABLE (TASK 3) ====================

@router.get("/accountant-performance")
async def get_accountant_performance_table(
    page: int = Query(default=1, ge=1, description="Page number"),
    page_size: int = Query(default=20, ge=1, le=100, description="Items per page"),
    sort_by: str = Query(default="total_collected", description="Sort field"),
    sort_order: str = Query(default="desc", description="Sort order (asc/desc)"),
    date_from: Optional[str] = Query(None, description="Start date YYYY-MM-DD"),
    date_to: Optional[str] = Query(None, description="End date YYYY-MM-DD"),
    accountant_id: Optional[str] = Query(None, description="Filter by accountant ID"),
    current_user: dict = Depends(get_current_user)
):
    """
    Get accountant performance table with pagination and filtering.
    TASK 3: Accountant Activity Table
    
    Admin/root can see all accountants, accountants see only themselves.
    """
    role = current_user.get("role", "").lower()
    user_id = current_user.get("id") or current_user.get("user_id")
    
    # Security: Non-admins can only see their own data
    if role == "accountant":
        accountant_id = user_id
    elif role not in ["admin", "root"]:
        logger.warning(f"⚠️ Unauthorized statistics access attempt by {current_user.get('email')}")
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied."
        )
    
    logger.info(f"👤 Accountant performance table generated by {current_user.get('email')}")
    
    try:
        school_id = current_user.get("school_id")
        
        if not school_id:
            raise HTTPException(status_code=400, detail="School context required")
        
        result = get_accountant_performance(
            school_id=school_id,
            page=page,
            page_size=page_size,
            sort_by=sort_by,
            sort_order=sort_order,
            date_from=date_from,
            date_to=date_to,
            accountant_id=accountant_id
        )
        
        return {"success": True, **result}
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Error getting performance table: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ==================== PAYMENT METHOD ANALYTICS (TASK 4) ====================

@router.get("/payment-method-stats")
async def get_payment_method_analytics(
    date_from: Optional[str] = Query(None, description="Start date YYYY-MM-DD"),
    date_to: Optional[str] = Query(None, description="End date YYYY-MM-DD"),
    current_user: dict = Depends(get_current_user)
):
    """
    Get payment method analytics with distribution.
    TASK 4: Payment Method Analytics
    
    Accessible by accountant, admin, root.
    """
    role = current_user.get("role", "").lower()
    
    if role not in ["accountant", "admin", "root"]:
        logger.warning(f"⚠️ Unauthorized statistics access attempt by {current_user.get('email')}")
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied."
        )
    
    logger.info(f"💳 Payment method analytics generated by {current_user.get('email')}")
    
    try:
        school_id = current_user.get("school_id")
        
        if not school_id:
            raise HTTPException(status_code=400, detail="School context required")
        
        result = get_payment_method_stats(
            school_id=school_id,
            date_from=date_from,
            date_to=date_to
        )
        
        return {"success": True, **result}
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Error getting payment method stats: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ==================== CLASS REVENUE STATS (TASK 5) ====================

@router.get("/class-revenue-stats")
async def get_class_revenue_statistics(
    date_from: Optional[str] = Query(None, description="Start date YYYY-MM-DD"),
    date_to: Optional[str] = Query(None, description="End date YYYY-MM-DD"),
    class_id: Optional[str] = Query(None, description="Filter by class ID"),
    current_user: dict = Depends(get_current_user)
):
    """
    Get revenue statistics per class.
    TASK 5: Class Revenue Statistics
    
    Accessible by accountant, admin, root.
    """
    role = current_user.get("role", "").lower()
    
    if role not in ["accountant", "admin", "root"]:
        logger.warning(f"⚠️ Unauthorized statistics access attempt by {current_user.get('email')}")
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied."
        )
    
    logger.info(f"🏫 Class revenue statistics calculated by {current_user.get('email')}")
    
    try:
        school_id = current_user.get("school_id")
        
        if not school_id:
            raise HTTPException(status_code=400, detail="School context required")
        
        result = get_class_revenue_stats(
            school_id=school_id,
            date_from=date_from,
            date_to=date_to,
            class_id=class_id
        )
        
        return {"success": True, **result}
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Error getting class revenue stats: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ==================== ACTIVITY TIMELINE (TASK 6) ====================

@router.get("/activity-timeline")
async def get_accounting_activity_timeline(
    page: int = Query(default=1, ge=1, description="Page number"),
    page_size: int = Query(default=20, ge=1, le=100, description="Items per page"),
    activity_types: Optional[str] = Query(None, description="Comma-separated activity types"),
    date_from: Optional[str] = Query(None, description="Start date YYYY-MM-DD"),
    date_to: Optional[str] = Query(None, description="End date YYYY-MM-DD"),
    accountant_id: Optional[str] = Query(None, description="Filter by accountant ID"),
    current_user: dict = Depends(get_current_user)
):
    """
    Get activity timeline showing all accounting events.
    TASK 6: Daily Activity Timeline
    
    Returns latest 100 activities by default with pagination.
    Admin/root see all, accountants see only their own.
    """
    role = current_user.get("role", "").lower()
    user_id = current_user.get("id") or current_user.get("user_id")
    
    # Security: Non-admins can only see their own data
    if role == "accountant":
        accountant_id = user_id
    elif role not in ["admin", "root"]:
        logger.warning(f"⚠️ Unauthorized statistics access attempt by {current_user.get('email')}")
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied."
        )
    
    logger.info(f"🕒 Accounting activity timeline generated by {current_user.get('email')}")
    
    try:
        school_id = current_user.get("school_id")
        
        if not school_id:
            raise HTTPException(status_code=400, detail="School context required")
        
        # Parse activity types
        types_list = None
        if activity_types:
            types_list = [t.strip() for t in activity_types.split(",")]
        
        result = get_activity_timeline(
            school_id=school_id,
            page=page,
            page_size=page_size,
            activity_types=types_list,
            date_from=date_from,
            date_to=date_to,
            accountant_id=accountant_id
        )
        
        return {"success": True, **result}
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Error getting activity timeline: {e}")
        raise HTTPException(status_code=500, detail=str(e))
