from io import BytesIO
from typing import Any

from bson import ObjectId
from PyPDF2 import PdfReader, PdfWriter

from app.services.fee_voucher_service import generate_student_fee_voucher_with_photo


def generate_school_vouchers_combined_pdf(school_id: str, db: Any) -> bytes:
    """Generate a combined PDF containing one fee voucher per student for the whole school.

    This function fetches all students for the given school and merges their individual
    voucher PDFs (generated by generate_student_fee_voucher_with_photo) into a single PDF.
    """
    writer = PdfWriter()
    school_obj_id = ObjectId(school_id) if not isinstance(school_id, ObjectId) else school_id

    students_cursor = db.students.find({"school_id": school_obj_id})

    for student in students_cursor:
        student_id = str(student.get("_id"))
        try:
            pdf_bytes = generate_student_fee_voucher_with_photo(student_id, school_id, db)
            if not pdf_bytes:
                continue
            reader = PdfReader(BytesIO(pdf_bytes))
            for page in reader.pages:
                writer.add_page(page)
        except Exception:
            # Skip students that fail to generate vouchers to allow majority completion
            continue

    out_buf = BytesIO()
    writer.write(out_buf)
    return out_buf.getvalue()
